### ISSUE TITLE
Compiling from source fails on Linux

### ISSUE THREAD

**Issue by nemasu** [clangen/musikcube#108]
I ran into 2 compilation problems (I tried master branch and also the latest release):

1) My ncurses include files are in /usr/include not /usr/include/ncursesw, so I changed the include file to reference the correct location.

2) Linking musikcube failed complaining it was missing pthreads reference,
so I added '-pthread' to src/musikcube/CMakeFiles/musikcube.dir/link.txt and it linked.

After I installed it, It segfaults when I try to run 'musikcube', here's the stacktrace:
```
 : Process 4337 (musikcube) of user 1002 dumped core.
                
                Stack trace of thread 4337:
                #0  0x00007f1cba36ec84 _nc_printf_string_sp (libncursesw.so.6)
                #1  0x00007f1cba368bc0 vwprintw (libncursesw.so.6)
                #2  0x00007f1cba368d27 wprintw (libncursesw.so.6)
                #3  0x00000000005056a7 _ZN8cursespp13DialogOverlay6RedrawEv (musikcube)
                #4  0x0000000000505a44 _ZN8cursespp13DialogOverlay8SetTitleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (musikcube)
                #5  0x00000000004afd42 _ZN5musik4cube14SettingsLayout23CheckShowFirstRunDialogEv (musikcube)
                #6  0x00000000004b0197 _ZN5musik4cube14SettingsLayout19OnVisibilityChangedEb (musikcube)
                #7  0x0000000000525e79 _ZN8cursespp6Window6CreateEv (musikcube)
                #8  0x000000000052526b _ZN8cursespp6Window28RecreateForUpdatedDimensionsEv (musikcube)
                #9  0x00000000004b9640 _ZN5musik4cube10MainLayout8OnLayoutEv (musikcube)
                #10 0x0000000000525bda _ZN8cursespp6Window6CreateEv (musikcube)
                #11 0x000000000052588c _ZN8cursespp6Window4ShowEv (musikcube)
                #12 0x000000000050ba19 _ZN8cursespp10LayoutBase4ShowEv (musikcube)
                #13 0x00000000004fb2e1 _ZN8cursespp3App12ChangeLayoutESt10shared_ptrINS_7ILayoutEE (musikcube)
                #14 0x00000000004fb5e2 _ZN8cursespp3App3RunESt10shared_ptrINS_7ILayoutEE (musikcube)

```

**Comment by clangen** [comment]
Yikes. Thanks for the report. Can you tell me which distro you're using?

**Comment by nemasu** [comment]
No problem.
Well, I'm using something I put together myself, so that probably wont helpful.
Other distros, like Arch, put their ncurses include files in the same place though.

Also, here's the linking error, it might help:

> [ 34%] Linking CXX executable ../../bin/musikcube
> /usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../../bin/plugins/libmusikcore.a(sqlite3.c.o): undefined reference to symbol 'pthread_mutexattr_settype@@GLIBC_2.2.5'
> /lib/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/musikcube/CMakeFiles/musikcube.dir/build.make:1332: bin/musikcube] Error 1
> make[1]: *** [CMakeFiles/Makefile2:234: src/musikcube/CMakeFiles/musikcube.dir/all] Error 2
> make: *** [Makefile:128: all] Error 2

**Comment by sauerbraten** [comment]
I didn't have the first problem described, but was also missing a pthread reference. Same output as @nemasu posted. Their fix did not work for me, however, [this](https://github.com/sauerbraten/musikcube/commit/21d8202794a04ca666e09b9d9bb8d049fd5f1b1c) made it compile. I also get a segmentation fault when running the program.

**Comment by sauerbraten** [comment]
By the way @clangen: I'm on Fedora 25 and this installed the dependencies for me: `sudo dnf install cmake boost-devel libogg-devel libvorbis-devel flac-devel faad2-devel ncurses-devel zlib-devel alsa-lib-devel pulseaudio-libs-devel libcurl-devel libmicrohttpd-devel lame-devel`

**Comment by captn3m0** [comment]
Faced similar issues:

1. ncurses is in `/usr/include` (ArchLinux)
2. `debug.cpp` is missing a reference to boost functional:

```
[  4%] Built target taglib
[  4%] Building CXX object src/core/CMakeFiles/musikcore.dir/debug.cpp.o
/home/nemo/projects/ubuntu_packages/musikcube/src/core/debug.cpp: In static member function ‘static void musik::debug::init()’:
/home/nemo/projects/ubuntu_packages/musikcube/src/core/debug.cpp:161:36: error: ‘bind’ is not a member of ‘std’
     thread_ = new std::thread(std::bind(&thread_proc));
                                    ^~~~
/home/nemo/projects/ubuntu_packages/musikcube/src/core/debug.cpp:161:36: note: suggested alternative: ‘rend’
     thread_ = new std::thread(std::bind(&thread_proc));
                                    ^~~~
                                    rend
make[2]: *** [src/core/CMakeFiles/musikcore.dir/build.make:63: src/core/CMakeFiles/musikcore.dir/debug.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:123: src/core/CMakeFiles/musikcore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

This is the diff I'm building with:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 757cfa3..741d34d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -24,7 +24,7 @@ ExternalProject_Add(taglib
     INSTALL_COMMAND make install
 )
 
-set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=c++14 -Wno-unused-result -Wno-deprecated-declarations")
+set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} "-std=c++14 -Wno-unused-result -Wno-deprecated-declarations -pthread")
 set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
 set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2")
 
diff --git a/src/core/debug.cpp b/src/core/debug.cpp
index 8569b39..8606e01 100755
--- a/src/core/debug.cpp
+++ b/src/core/debug.cpp
@@ -35,7 +35,7 @@
 #include "pch.hpp"
 
 #include <core/debug.h>
-
+#include <functional>
 #include <string>
 #include <queue>
 #include <thread>
diff --git a/src/musikcube/cursespp/curses_config.h b/src/musikcube/cursespp/curses_config.h
index 1a80ccf..9f47d08 100755
--- a/src/musikcube/cursespp/curses_config.h
+++ b/src/musikcube/cursespp/curses_config.h
@@ -46,6 +46,6 @@
     #include <curses.h>
     #include <panel.h>
 #else
-    #include <ncursesw/curses.h>
-    #include <ncursesw/panel.h>
+    #include <curses.h>
+    #include <panel.h>
 #endif
```

3. Same pthread issue as above.

It still segfaults at the same place:

```
#0  0x00007ffff6ab6f38 in _nc_printf_string_sp () from /usr/lib/libncursesw.so.6
#1  0x00007ffff6ab0be0 in vwprintw () from /usr/lib/libncursesw.so.6
#2  0x00007ffff6ab0d74 in wprintw () from /usr/lib/libncursesw.so.6
#3  0x00005555558d7a4e in cursespp::DialogOverlay::Redraw() ()
#4  0x00005555558d73f2 in cursespp::DialogOverlay::Layout() ()
#5  0x00005555558d7457 in cursespp::DialogOverlay::SetTitle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x0000555555859486 in musik::cube::SettingsLayout::CheckShowFirstRunDialog() ()
#7  0x000055555585921b in musik::cube::SettingsLayout::OnVisibilityChanged(bool) ()
#8  0x00005555558f9aec in cursespp::Window::Create() ()
#9  0x00005555558f9116 in cursespp::Window::Recreate() ()
#10 0x00005555558f87f3 in cursespp::Window::RecreateForUpdatedDimensions() ()
#11 0x00005555558f8955 in cursespp::Window::MoveAndResize(int, int, int, int) ()
#12 0x000055555586b211 in musik::cube::MainLayout::OnLayout() ()
#13 0x00005555558db647 in cursespp::LayoutBase::Layout() ()
#14 0x00005555558db5a5 in cursespp::LayoutBase::Show() ()
#15 0x00005555558f9ab0 in cursespp::Window::Create() ()
#16 0x00005555558f90a1 in cursespp::Window::Show() ()
#17 0x00005555558db58c in cursespp::LayoutBase::Show() ()
#18 0x00005555558ce565 in cursespp::App::ChangeLayout(std::shared_ptr<cursespp::ILayout>) ()
#19 0x00005555558cd9c3 in cursespp::App::Run(std::shared_ptr<cursespp::ILayout>) ()
#20 0x000055555582d2f3 in main ()
```

**Comment by clangen** [comment]
Yikes. Thanks for bringing this up. Took a quick peek during lunch and I think I see the issue. Will get a fix checked in this evening after work!

**Comment by anupamk** [comment]
@captn3mo faced identical build issue, with identical fixes as well. this is on an archlinux machine. i also see the same signal-11 behavior during startup.

issue #117 for reference.

**Comment by anupamk** [comment]
sorry for the noise, the issue number is #114 and not #117 as mentioned above.

**Comment by clangen** [comment]
@nemasu @sauerbraten @captn3m0 @anupamk -- please pull and try again. I think I fixed the startup bug in Fedora and Arch, and also incorporated the minor code changes mentioned as part of this thread. Things should compile out of the box now.

**Comment by nemasu** [comment]
@clangen I still run into the cursesw problem because I don't use Arch. How about using something like this? [FindCurses](https://cmake.org/cmake/help/v3.7/module/FindCurses.html)

I can confirm that it no longer segfaults on startup though!

**Comment by clangen** [comment]
@nemasu thanks for the heads up, I will look into FindCurses. 

That said, I installed Fedora 26 virtual machine a few minutes ago, and was able to compile and run the musikcube `master` branch without any additional tweaks. Are you now getting linker or compiler errors related to ncurses after the latest couple commits?

**Comment by sauerbraten** [comment]
@clangen I can confirm it compiles with no issues in Fedora now. However, after using the program for a 
 bit (playing music, navigating through the different views) it segfaults again. I'm not sure how to get the stack trace. Let me know how to do that if you need me to reproduce the problem.

**Comment by nemasu** [comment]
@clangen Same compiler errors, still can't find ncursesw directory (I don't have /etc/arch-release, so NO_NCURSESW is never set).

**Comment by clangen** [comment]
@sauerbraten the best way is probably to recompile with debug flags, run the app, attach a debugger, then run until it crashes. 

Recompile with debug flags, then run:
* `cmake -DCMAKE_BUILD_TYPE=Debug .`
* `make -j4`
* `./bin/musikcube`

Get the PID of the process:
* `ps xao pid,comm | grep musikcube` 

Attach the debugger:
* `gdb`
* `attach <pid>`
* `continue`

Now see if you can make it crash! If you can, attach the gdb stack trace here.

What were you doing when you observed the crash? I am noticing some other weirdness related to focus tracking that doesn't seem to be issues in the Debian/Ubuntu version, or PDCurses for Windows. Maybe it's somehow related.

**Comment by sauerbraten** [comment]
@clangen Here you go:

```#0  0x00007f0a5de2f118 in _nc_printf_string_sp () from /lib64/libncursesw.so.6
#1  0x00007f0a5de28c60 in vwprintw () from /lib64/libncursesw.so.6
#2  0x00007f0a5de28df4 in wprintw () from /lib64/libncursesw.so.6
#3  0x0000000000721d72 in writePlayingFormat (w=0x0, displayCache=..., width=69) at /home/sauerbraten/musikcube/src/musikcube/app/window/TransportWindow.cpp:288
#4  0x0000000000722b05 in musik::cube::TransportWindow::Update (this=0x12ee990, timeMode=musik::cube::TransportWindow::TimeSmooth) at /home/sauerbraten/musikcube/src/musikcube/app/window/TransportWindow.cpp:486
#5  0x000000000072263e in musik::cube::TransportWindow::ProcessMessage (this=0x12ee990, message=...) at /home/sauerbraten/musikcube/src/musikcube/app/window/TransportWindow.cpp:409
#6  0x000000000078b631 in musik::core::runtime::MessageQueue::Dispatch (this=0xba4b40 <messageQueue>, message=std::shared_ptr (count 2, weak 0) 0x136de90)
    at /home/sauerbraten/musikcube/src/core/runtime/MessageQueue.cpp:242
#7  0x000000000078aa2f in musik::core::runtime::MessageQueue::Dispatch (this=0xba4b40 <messageQueue>) at /home/sauerbraten/musikcube/src/core/runtime/MessageQueue.cpp:115
#8  0x000000000072a1f2 in cursespp::App::Run (this=0x7fff46be56a0, layout=std::shared_ptr (count 4, weak 1) 0x12835d8) at /home/sauerbraten/musikcube/src/musikcube/cursespp/App.cpp:336
#9  0x00000000006945b0 in main (argc=1, argv=0x7fff46be60c8) at /home/sauerbraten/musikcube/src/musikcube/Main.cpp:197
````
It reliably happens when switching to the settings view after starting playback of any file.

I'm not sure what you mean by weirdness related to focus, but I noticed the border around the tracks pane in the browser view not turning red, and the border of the artists pane staying red, even when not in focus. The volume and progress bar become red and white again with gaining and losing focus, as I'd expect. Is that what you mean?

**Comment by clangen** [comment]
@sauerbraten awesome, thanks for the stacktrace. The bug should be fixed now in `master`, along with the weird focusing issue.

It seems that ncurses on Fedora and Arch are more strict than on other platforms. I'd almost forgotten how fun cross-platform, cross-distro development can be. :)

**Comment by Gobln** [comment]
Manajro user here.
I'm still getting this error.
`/home/goblin/musikcube/src/musikcube/cursespp/curses_config.h:46:14: fatal error: ncursesw/curses.h: No such file or directory
     #include <ncursesw/curses.h>
              ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/musikcube/CMakeFiles/musikcube.dir/build.make:63: src/musikcube/CMakeFiles/musikcube.dir/Main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:234: src/musikcube/CMakeFiles/musikcube.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by clangen** [comment]
@nemasu, @Gobln are you both on Fedora 26? I should probably split this issue into a couple different ones for the different platforms.

**Comment by sauerbraten** [comment]
@clangen @Gobln said he uses Manjaro, which is basically Arch I think. And @nemasu said:

> Well, I'm using something I put together myself [...]

Soooo...

**Comment by Gobln** [comment]
Correct, I'm on what is basically an Arch setup for all intensive purposes. A lot of the issues seem to be around the ncurses stuff being in /usr/include and not their own directory. Curses.h IS in /include, I've just checked.

**Comment by clangen** [comment]
Just a little background on the remaining issue in this ticket: there are two versions of the ncurses headers, one which has "wide character" support, and one that doesn't. musikcube requires the wide version.

In many cases (Debian/Ubuntu), Linux distributions have both. The non-wide version is usually in `/usr/include`, or whatever, and the wide-version is is `/usr/include/ncursesw`. 

ArchLinux (and variants) seem to only ship the "wide" version. But it exists in in `/usr/include`, and not `/usr/include/ncursesw` as it does it other distros. See https://bugs.archlinux.org/task/17590

I'm trying to figure out the best way to ensure we always include the wide-character version as part of the CMake process. The [FindCurses](https://cmake.org/cmake/help/v3.6/module/FindCurses.html) macro was recommended, but the docs don't mention how to explicitly specify the wide-version. 

After Googling a bit it looks like we may be able to specify `CURSES_NEED_WIDE` in CMake before calling FindCurses, but this appears to be non-standard (or maybe not even supported). 

I'm by no means a CMake expert, so this is taking me a while to find a straight-forward solution.

**Comment by clangen** [comment]
@nemasu @Gobln I'm still trying to figure out a better solution, but I put in a quick fix. If you pull from master, you should be able to do:

`cmake -DNO_NCURSESW=1 .` followed by `make` -- hopefully it compiles now without code changes.

**Comment by clangen** [comment]
OK, I've added explicit detection for Manjaro Linux so this should no longer be a problem for that distro. I'm also keeping the `-DNO_NCURSESW=1` flag so other similar distros can compile without making code changes. I've also updated the build instructions to include a `troubleshooting` section that describes this issue in detail: https://github.com/clangen/musikcube/wiki/building

I'm going to go ahead and resolve this issue for now.

Note: detection of Manjaro was added AFTER the 0.22.0 release, so you will need to compile from master if you need the auto-detection support. The `DNO_NCURSESW=1` flag DOES exist in 0.22.0, however.
