### ISSUE TITLE
Trouble compiling on FreeBSD

### ISSUE THREAD

**Issue by ghost** [clangen/musikcube#172]
I run pkg install boost-all under FreeBSD. Getting the following error during make.

```
[  5%] Building CXX object src/core/CMakeFiles/musikcore.dir/audio/Buffer.cpp.o
In file included from /home/gregf/musikcube/src/core/audio/Buffer.cpp:37:
In file included from /home/gregf/musikcube/src/core/audio/Buffer.h:37:
/home/gregf/musikcube/src/core/config.h:42:10: fatal error: 'boost/format.hpp' file not found
#include <boost/format.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make[1]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make: stopped in /usr/home/gregf/musikcube
```

**Comment by clangen** [comment]
musikcube has a handful of dependencies. I don't currently have a FreeBSD install, but most of the dependencies should be pretty common.

They are listed here, for multiple Linux distributions, which should help you: https://github.com/clangen/musikcube/wiki/building

If you manage to get it building on FreeBSD, it'd be great if you could supply the list of package names so I can add it to the wiki :)

**Comment by ghost** [comment]
I did go through that install what I thought needed to be installed. I do have boost/format.hpp on my system, but its in `/usr/local/include/boost/format.hpp`. I wonder if the location is a issue with how you include format.hpp? I'm not a c++ dev so I have no idea how this works.

**Comment by clangen** [comment]
Huh. I guess maybe `/usr/local` insn't included in the search path by default. If you edit the `CMakeFiles.txt` file in the root directory, you'll find this section of code starting around line 82:

```
if (CMAKE_SYSTEM_NAME MATCHES "Darwin")
  link_directories ("/usr/local/lib")
  include_directories("/usr/local/include")
  link_directories ("/opt/local/lib")
  include_directories("/opt/local/include")
endif ()
```

Try to change it to this (comment out the conditional check):

```
#if (CMAKE_SYSTEM_NAME MATCHES "Darwin")
  link_directories ("/usr/local/lib")
  include_directories("/usr/local/include")
  link_directories ("/opt/local/lib")
  include_directories("/opt/local/include")
#endif ()
```

If you re-run `cmake .` and then `make`, does it work now?

**Comment by ghost** [comment]
It made it past the previous error and is now says this.

```
/home/gregf/musikcube/src/musikcube/cursespp/curses_config.h:46:14: fatal error: 'ncursesw/curses.h' file not found
```

On FreeBSD I have the following.

```
/usr/local/include/ncurses/curses.h
```

**Comment by clangen** [comment]
I've seen this issue in a couple Linux distros as well. Try adding `-DNO_NCURSESW ` to your `cmake` command:

`cmake -DNO_NCURSESW .`

A bit of info at the very bottom of this page: https://github.com/clangen/musikcube/wiki/building

Let me know if it works, I'll update the documentation accordingly.

**Comment by ghost** [comment]
Sorry to be such a pita. I can't seem to run cmake like that even on a fresh checkout.

```
$ cmake -DNO_NCURSESW .                                                                                                                      
Parse error in command line argument: -DNO_NCURSESW                                                                                                                                      
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```

```
cmake version 3.9.6
```

**Comment by clangen** [comment]
You're not a pita at all -- these sorts of problems are just part of cross-platform app development! :)

I think I made a mistake in the documentation, try `cmake -DNO_NCURSESW=true .` instead. Does that get you further?

**Comment by ghost** [comment]
I just did a fresh check out to try both of these fixes at once and I no longer see `CMakeFiles.txt` in the repo?

**Comment by clangen** [comment]
Hmm, it's definitely still there: https://github.com/clangen/musikcube/blob/master/CMakeLists.txt

How did you clone the repo?

**Comment by ghost** [comment]
Sorry i'm being blind. I was looking for CMakeFiles.txt for some reason. Building now.

**Comment by ghost** [comment]
Looks like to fully compiles now just doesn't link?

```
[ 59%] Building CXX object src/musikcube/CMakeFiles/musikcube.dir/cursespp/TextLabel.cpp.o                                                                                               
[ 60%] Building CXX object src/musikcube/CMakeFiles/musikcube.dir/cursespp/ToastOverlay.cpp.o                                                                                            
[ 61%] Building CXX object src/musikcube/CMakeFiles/musikcube.dir/cursespp/Window.cpp.o                                                                                                  
[ 61%] Linking CXX executable ../../bin/musikcube                                                                                                                                        
/usr/bin/ld: cannot find -ldl                                                                                                                                                            
c++: error: linker command failed with exit code 1 (use -v to see invocation)                                                                                                            
*** Error code 1                                                                                                                                                                         
                                                                                                                                                                                         
Stop.
make[2]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make[1]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make: stopped in /usr/home/gregf/musikcube
```

**Comment by clangen** [comment]
Ooh, looks like we're getting somewhere now. Had to do a little bit of digging, but it looks like this functionality is already included in `libc` on FreeBSD. So... another CMakeLists.txt edit. 

Starting around line 64 in CMakeLists.txt is this section:

```
set (musikcube_LINK_LIBS
  ${linux_LINK_LIBS}
  ${BOOST_LINK_LIBS}
  dl
  curl
  pthread
)
```

Try to remove the `dl` part, so it's just:

```
set (musikcube_LINK_LIBS
  ${linux_LINK_LIBS}
  ${BOOST_LINK_LIBS}
  curl
  pthread
)
```

Sorry for the churn. If we manage to get through this, I'll have you send me a patch so I can fix the CMakeLists so it'll work out of the box for future users.

**Comment by ghost** [comment]
Ok that got us a bit further.

```
[ 99%] Built target flacdecoder                                                                                                                                                          
Scanning dependencies of target coreaudioout                                                                                                                                             
[ 99%] Building CXX object src/plugins/coreaudioout/CMakeFiles/coreaudioout.dir/coreaudioout_plugin.cpp.o                                                                                
In file included from /home/gregf/musikcube/src/plugins/coreaudioout/coreaudioout_plugin.cpp:39:                                                                                         
/home/gregf/musikcube/src/plugins/coreaudioout/CoreAudioOut.h:41:10: fatal error: 'AudioToolbox/AudioQueue.h' file not found
#include <AudioToolbox/AudioQueue.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make[1]: stopped in /usr/home/gregf/musikcube
*** Error code 1

Stop.
make: stopped in /usr/home/gregf/musikcube

```

**Comment by clangen** [comment]
Oh. Hmm. Does FreeBSD support ALSA? I really need to get a VM up and running so I can play with it. At any rate, around line 113 in CMakeLists you'll find this:

```
if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  add_subdirectory(src/plugins/alsaout)
  add_subdirectory(src/plugins/pulseout)
else (CMAKE_SYSTEM_NAME MATCHES "Linux")
  # macos
  add_subdirectory(src/plugins/coreaudioout)
endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
```

Let's masquerade as Linux and try compile ALSA and FreeBSD by commenting out some stuff:

```
#if (CMAKE_SYSTEM_NAME MATCHES "Linux")
  add_subdirectory(src/plugins/alsaout)
  add_subdirectory(src/plugins/pulseout)
#else (CMAKE_SYSTEM_NAME MATCHES "Linux")
#  # macos
#  add_subdirectory(src/plugins/coreaudioout)
#endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
```

If you see failures with ALSA, try only Pulse:

```
#if (CMAKE_SYSTEM_NAME MATCHES "Linux")
#  add_subdirectory(src/plugins/alsaout)
  add_subdirectory(src/plugins/pulseout)
#else (CMAKE_SYSTEM_NAME MATCHES "Linux")
#  # macos
#  add_subdirectory(src/plugins/coreaudioout)
#endif (CMAKE_SYSTEM_NAME MATCHES "Linux")
```

**Comment by ghost** [comment]
I think it supports both alsa and pulse.

It compiled clean I ran make install and I get this.

```
[100%] Built target pulseout                                                                                                                                                             
Install the project...                                                                                                                                                                   
-- Install configuration: ""                                                                                                                                                             
-- Installing: /usr/local/share/musikcube/musikcube                                                                                                                                      
CMake Error at cmake_install.cmake:35 (file):                                                                                                                                            
  file INSTALL cannot find
  "/usr/home/gregf/musikcube/bin/plugins/libcoreaudioout.dylib".

                                                                                                                                                                                         
*** Error code 1                                                                                                                                                                         

Stop.
make: stopped in /usr/home/gregf/musikcube
```

**Comment by ghost** [comment]
I tried to `cd bin/` then run `musikcube` without make install since it was failing and it segfaults. Here's the core dump.

https://filebin.pw/YCxBI/

**Comment by clangen** [comment]
Yep, I just installed a FreeBSD VM and managed to get it compile, but it crashes immediately. I'll see if I can figure out what's going on.

**Comment by clangen** [comment]
OK. So... I got it compiling, linking, and running. Problem is that it doesn't seem to work very well. I can start it up, add some music, and play -- but only with the `PulseAudio` output driver. The `ALSA` driver is crashing. Also, I can't get it to shut down cleanly, which causes settings to get lost. 

I'll keep working on this over the next couple days. Hopefully I can get it running well.

Feel free to pull `master` and let me know if it works for you.

One more thing: make sure you use a terminal that supports UTF8, otherwise the UI may look a bit garbled. We use some UTF8 characters for certain UI elements.

**Comment by ghost** [comment]
I just did a git pull and recompiled. It now runs and plays music with pulseaudio installed. It would be great if you could support oss (FreeBSD's sound system) out of the box, so we don't have to install pulseaudio. It's not something most FreeBSD users use. That being said it works, like you said it is hanging on shutdown. If you can get some more of this cleaned up I have a port ready I would be happy to submit on the next release.

Oh, and of course thank you!

**Comment by clangen** [comment]
OK, I pushed some changes to `master` that should allow for clean app shutdown. The version of `libmicrohttpd` that ships on the current version of FreeBSD seems to be problematic -- not exactly sure why -- but it hangs when shutting down. Newer versions don't have this problem. 

I updated the server's build scripts to fetch, compile, and link against a sandboxed copy (as to not pollute the OS itself with a different version of this library). It seems to be working fine now.

I'll try to take a crack at an OSS output plugin over the next few days -- hopefully it's relatively straight forward.

**Comment by ghost** [comment]
I'll work on getting a newer version of libmicrohttpd into FreeBSD today

**Comment by ghost** [comment]
Might want to also look at sndiod. It's supported by all the BSD's. Not sure if that is a  better option than just OSS.

http://www.sndio.org/

**Comment by clangen** [comment]
Nice, thanks for the `sndio` heads up. It was surprisingly easy to integrate with -- probably the easiest of all the audio output APIs I've worked with! I just pushed some new changes to `master` that allow you to select `sndio` as the output driver on FreeBSD. 

There may be bugs and/or memory leaks, but from the surface it seems to be working well. Feel free to pull `master` and give it a shot. I'll be testing it more over the weekend.

**Comment by ghost** [comment]
Do I have to do something specific to get sndio as my default? Or will it just use that?

**Comment by ghost** [comment]
OK Two issues I have found.

* /usr/local/bin/musikcube is a bash script that points to #!/bin/bash this should be #!/usr/bin/env bash. Bash is in /usr/local in BSD.

* Having some utf8 issues. Same terminal and font on linux doesn't have it, not sure the cause.

![2017-12-22-210507_1680x1025_scrot](https://user-images.githubusercontent.com/980/34316088-fb620ce6-e75b-11e7-8027-c7378f201864.png)

I'm using rxvt-unicode

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE=C
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

**Comment by ghost** [comment]
I tried a few other consoles with the same results. Other utf8 characters are displaying fine in my prompt and tmux status bar.

**Comment by clangen** [comment]
Thanks for the script fix!

Regarding the box drawing issues -- hmm, I'm not sure. `urxvt` seems to be working fine on my end, of course. It's especially weird because they seem to draw fine for you in _some_ cases -- around the corners of the views they seem fine. What font are you using? Any sort of rxvt config you could provide me with may help.

**Comment by ghost** [comment]
The font is part of nerd-fonts on github, you can find the font i'm using in my config [here](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Mononoki/complete).

I have tried other non patched fonts like inconsolata, droid & terminus. All of these worked fine on linux with musikcube.

If you have it working on your end could you share your settings?

```
URxvt*font: xft:mononoki nerd font:size=12:weight=medium:antialias=true:autohint=true
URxvt*scrollBar: false
URxvt*perl-ext-common: default,matcher
URxvt*url-launcher: firefox
URxvt*matcher.button: 1
URxvt*letterSpace: -1
URxvt*urgentOnBell: true
URxvt*scrollTtyKeypress: true
URxvt*scrollTtyOutput: false
URxvt*scrollWithBuffer: false
URxvt*termName: rxvt-256color
URxvt*buffered: true
URxvt*print-pipe: cat > $HOME/$(echo urxvt.dump.$(date +'%Y%M%d%H%m%S'))
URxvt*fading:  10
URxvt*visualBell: false
```

**Comment by clangen** [comment]
Hmm, your config works fine for me as well. I don't have any special settings on my end -- I just installed urxvt and fired it up with defaults.

Do other terminal emulators seem to work for you?

Also, do you see these weird artifacts on, say, the settings screen? Or just in the music library?

**Comment by ghost** [comment]
Everywhere those vertical lines are shown I'm seeing the problem. I have tried several terminals (xfce4-terminal, urxvt, qterminal, xterm and fonts.

**Comment by ghost** [comment]
Just on the off chance it matters, I'm running 12-CURRENT, because that is the only version where my video drivers are supported right now.

**Comment by ghost** [comment]
Another note, ranger & weechat both have those same type of vertical lines and they draw fine.

![2017-12-23-092628_840x1025_scrot](https://user-images.githubusercontent.com/980/34320248-5f073aac-e7c3-11e7-8b43-188632170f2f.png)

**Comment by ghost** [comment]
My friend has a fresh install of PC-BSD I asked him to install musikcube so I could see if it was just me. He's having the same issue.

![musikcube2017-12-23](https://user-images.githubusercontent.com/980/34320302-0840d618-e7c5-11e7-85f5-a6afc20be788.png)

**Comment by clangen** [comment]
Hmm. Still struggling to reproduce it on my end. You mentioned he has PC-BSD, which the build scripts don't currently support -- did you just send him some binaries? If that's the case, maybe you can send me your binaries and I can try them over here on my VM.

**Comment by ghost** [comment]
PC-BSD is just a desktop version of FreeBSD. It compiled fine on  his system earlier this morning. It is also based on 12-current, so maybe it has something to do with 12-current and your not seeing it because your probably using 11.1?

**Comment by clangen** [comment]
Ah hah, that could be it. I'll see about getting a 12-current installation up and running in a VM to see if I can repro there.

**Comment by clangen** [comment]
I installed PC-BSD (which I guess is called TrueOS now?) and the boxes are still drawing fine on my end. Bleh.

**Comment by miker** [comment]
Hello. I'm the one running TrueOS having the same issue. I'm getting the same odd behaviour with the vertical pipes with a new user I created to make sure it wasn't something odd with a dotfile or something.

![musikcubenewuser](https://user-images.githubusercontent.com/8848/34327315-1940f1a8-e88f-11e7-9b55-2d600b10e7f7.png)

This user is using the mate desktop, and the csh shell. The dark screenshot gregf provided for me above is using mate-terminal with zsh. Both of my screenshots _should_ be using the "monospace regular" font. 

I'm happy to test any ideas that we come up with.

(You are correct PC-BSD is now TrueOS.)

**Comment by clangen** [comment]
Man, this is so strange. I tried both the current version of TrueOS, and also the unsable one. Everything's fine on my end. Here's a screenshot running mate-terminal with zsh:

![image](https://user-images.githubusercontent.com/2031666/34328962-e4ed5580-e8a3-11e7-914a-cd4ddcf264b9.png)

I'm sort of out of ideas. Maybe you can share the output of the `locale` command? I'm just using standard, decades-old curses functionality to draw boxes, but maybe there's some sort of character encoding issue.

If you have a chance, can you try one more thing? Open up `<root>/src/musikcube/cursespp/ListWindow.cpp` and change line `80` 

from:
`if (this->showScrollbar) { `

To:
`if (false) {`

Then recompile and run. Maybe somehow the scroll indicator is screwing things up.

**Comment by ghost** [comment]
Mike and I have been discussing this together. We are both using a alpha quality video driver for our setups. We think there could be a corruption issue with drawing in the driver possibly? Trying to find someone who is not using the driver to test to confirm. Get back to you after the holidays. Merry Christmas and thanks for all the support.

**Comment by ghost** [comment]
@clangen  Wow, good call on that. That seems to have fixed the drawing issue for me.

![2017-12-24-154831_1680x511_scrot](https://user-images.githubusercontent.com/980/34329136-ea314ed4-e8c1-11e7-8335-8a0e0a7d9fa6.png)

**Comment by ghost** [comment]
I have this installed `ncurses-6.0.0s20171007_1`

**Comment by clangen** [comment]
Whoa. OK, at least I know where to start looking now. I'll see what I can figure out now.

Happy holidays, and thanks for the help!

**Comment by ghost** [comment]
I'm around all day today and part of the day tomorrow so feel free to hit me up if you want me to test something

**Comment by ghost** [comment]
Just a heads up, I tried updating ncurses to 20171223 and recompiling musikcube and that didn't change anything.

**Comment by miker** [comment]
Awesome job  you two.

**Comment by clangen** [comment]
OK, I just pushed some changes that *may* fix the problem. It's hard to tell, because I can't reproduce it to begin with. Out of curiosity, what type of hardware are you guys running on?

**Comment by miker** [comment]
I'm on a 4 or 5 year old Toshiba laptop with an Intel Haswell i5 w/integrated graphics.

**Comment by ghost** [comment]
I'm using an Amd fx 8350 with a radeon rx 580, compiling now let you know soon.

**Comment by clangen** [comment]
32-bit BSD installs? or 64?

**Comment by ghost** [comment]
I'm 64 bit, pretty sure Mike is as well. Sorry to say but that didn't fix the issue. :(

**Comment by miker** [comment]
TrueOS is 64bit only. (yes 64 bit)

**Comment by clangen** [comment]
Yeah, my fix probably would have only fixed issues on 32-bit installs. I'll keep thinking on it. Thanks for trying that fix tho! :)

**Comment by clangen** [comment]
OK, I pushed another change. I think this one has a better chance of fixing the issue. Give it a go whenever you have a chance!

**Comment by ghost** [comment]
Sorry to say that did not solve it either. Merry Christmas buddy. Enjoy your day!

**Comment by clangen** [comment]
Pushed another try -- give it a go whenever. :)

This feels like being back in college, randomly trying minor changes hoping it'll start working for reasons beyond my comprehension.

**Comment by ghost** [comment]
Sorry for the long delay I been busy. That last push did not fix it either. I wonder if I can get your email so we can talk in private and possibly give you ssh access to a box its broke on? Not sure if that would help you?

**Comment by clangen** [comment]
That would be awesome @gregf  -- probably way more productive than guessing and checking over this thread. My email address is casey[dot]langen[at]gmail . com

**Comment by ghost** [comment]
libmicrohttpd has been updated to the latest version in FreeBSD, so you may be able to remove it from the build process if you want.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224535

**Comment by clangen** [comment]
FYI, I just released 0.35.0 that includes FreeBSD and sndio support. I've disabled scrollbars for now, until I have manage to get access to a system that reproduces the issue.

https://github.com/clangen/musikcube/releases

**Comment by ghost** [comment]
Thank you for letting me know about the release. I'll work on adding it to
FreeBSD this week. I'm having some issues with my Firewall not forwading port 22
for some reason. Soon as I have time to sort that out I'll give you access
I been kinda busy.

**Comment by clangen** [comment]
Awesome, sounds good!

**Comment by ghost** [comment]
Hey sorry for the extended delay life got in the way for a bit. I think I might have found an issue with my box previous that would cause the weird utf8 issue. Can you tell me how to enable the scrollbar on FreeBSD so I can test and see if that was it? If not I'll give you ssh like we spoke about previously. Thank you.

**Comment by clangen** [comment]
Hey @gregf, good to see you again. You can try to enable the scrollbars in `Scrollbar.cpp`, here: https://github.com/clangen/musikcube/blob/master/src/musikcube/cursespp/Scrollbar.cpp

Remove the `#ifndef __FreeBSD__` on line 41, and the corresponding `#endif` on line 86.

**Comment by ghost** [comment]
BTW, libmicrohttpd is updated now in FreeBSD, so you might not need to bundle it anymore. Just a thought.

**Comment by ghost** [comment]
Sadly my fix didn't solve anything i'll send you a email later with ssh instructions

**Comment by clangen** [comment]
Finally fixed.
