### ISSUE TITLE
How to run musikcube in terminal (Windows).

### ISSUE THREAD

**Issue by 237dmitry** [clangen/musikcube#417]
How can I launch musikcube.exe in a terminal in Windows? It's not about musikcube-cmd.exe, since it is devoid of custom theme selection settings and in addition, it loads the processor very much in terminals other than the standard one (cmd.exe). If you just run musikcube.exe, then the application opens in a separate window... But who nowadays uses standart host? ConEmu, alacritty, and Windows Terminal have long been in use.

**Comment by william-roy** [comment]
I run musikcube-cmd.exe in an MSYS2 shell in Windows Terminal—it works perfectly and uses the shell's theme.

**Comment by 237dmitry** [comment]
> I run musikcube-cmd.exe in an MSYS2 shell in Windows Terminal

I don't quite understand why I need MSYS2, when on one laptop Linux, and on the other Windows. The problem is that in Windows Terminal it is impossible to start musikcube.exe, and only musikcube-cmd.exe. But musikcube-cmd.exe in wt, heavily loads the cpu and in addition, there is no custom style selection setting. Therefore, we have to adjust the design of the terminal to the design of the player, which in my opinion is like pulling pants over head.

![musikcube](https://user-images.githubusercontent.com/78153320/110219391-e7f73500-7ecf-11eb-9b97-4ff6dad2362a.png)

**Comment by william-roy** [comment]
>I don't quite understand why I need MSYS2

You don't, I was just sharing how I happen to use it.

>But musikcube-cmd.exe in wt, heavily loads the cpu 

That isn't the case on my machine, but I use a remote library running on my home server. Maybe it is taking that amount of CPU because it's indexing your library? See below:
![Screenshot 2021-03-06 154949](https://user-images.githubusercontent.com/51927032/110220525-2bcc4900-7e94-11eb-89d5-b28e67ee7058.png)

>Therefore, we have to adjust the design of the terminal to the design of the player, which in my opinion is like pulling pants over head.

Yeah, it might seem crazy to setup a shell config just for musikcube, but how often are you going to be opening and closing musikcube within another shell? For me, it's easier to have the settings for it in one place.

**Comment by clangen** [comment]
As far as I know, standard Windows cmd.exe/conhost stuff does not support extended palettes, and does not provide an ability to change defined colors on the fly. I may have to play around with this some more, but that was my experience a while back when I was playing with it. Because of this, themes are currently unsupported in this use case.

The more concerning issue is the high CPU usage using Windows Terminal. I'll try to find some time this weekend to see if I can reproduce that particular issue.

**Comment by clangen** [comment]
This should fix the high CPU usage bug: https://github.com/clangen/musikcube/commit/95420b83590a7a4c4f44b6e34270b4f4664228fa

**Comment by brian6932** [comment]
This is still an issue, why was it closed?
I don't see any reason why musikcube should launch it's own term here

OS: Windows 10
Shell: pwsh 7.3.0-preview.8
Term: alacritty 0.10.1 (2844606)

**Comment by clangen** [comment]
@brian6932 run the included `musikcube-cmd.exe` instead of `musikcube.exe` in your command shell, it'll open in-place.

**Comment by brian6932** [comment]
Yep, that fixed it, thank you, and sorry for the bump

~~Ok so this must be an issue with the scoop package, as that wasn't shimmed, I opened a PR with the fixes~~
The PR has been merged
