### ISSUE TITLE
Search/Filtering with accented characters not working

### ISSUE THREAD

**Issue by khagaroth** [clangen/musikcube#564]
I'm not a programmer, but with my limited coding skill, this section of src/musikcore/db/SqliteExtensions.cpp doesn't look right (a string in an integer type value?):
```
typedef UINT8_TYPE u8;             /* 1-byte unsigned integer */
typedef UINT32_TYPE u32;           /* 4-byte unsigned integer */

/*
** Mapping from accented UTF8 sequence to a regular english char
*/
static std::unordered_map<u32, u32> accentToChar = {
    { (u32)192 /* À */ , (u32)'A' },
    { (u32)193 /* Á */ , (u32)'A' },
    { (u32)194 /* Â */ , (u32)'A' },
    { (u32)195 /* Ã */ , (u32)'A' },
...
```

**Comment by clangen** [comment]
Thanks for bringing this to my attention. It looks like the code I added to support this in the past doesn't support all use cases. I'm working on a fix here, and it seems to be working well on Windows: https://github.com/clangen/musikcube/pull/565

I still need to test UNIX platforms, but I think this should be fixed in the next release.

**Comment by clangen** [comment]
Fixed in https://github.com/clangen/musikcube/releases/tag/0.99.1

**Comment by khagaroth** [comment]
This still doesn't work in 0.99.2.

Š is completely missing from the first two tables, but the other accents that are there don't work either.

And as I said in the first report, shouldn't all the u32 values be integers and not strings?

**Comment by clangen** [comment]
OK, I think I'm going to need some more info because this is working fine for me across 4 platforms. Here's a screenshot on macOS:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2031666/209579031-f464f14f-5809-46aa-a0fe-06e13c90bc70.png">

What values do you have for tags, and what values are you searching for? If there are omissions from the table we can add them easily, but I need to be able to reproduce the issue to figure out what's going on.

> And as I said in the first report, shouldn't all the u32 values be integers and not strings?

No, because UTF8 is a variable width encoding, and each code point is between 1 and 4 bytes -- therefore we represent them as a single 32 bit value instead of an 8 bit `char` (or a string with a null terminator, as this would be much more cumbersome to deal with)

As for reverse lookup, `strcspn` is used, so they are all packed into strings (`const char *`).

**Comment by clangen** [comment]
I see you're right, `Š` is omitted in the reverse lookup. We can get that and other omissions added to the table and get a new build out. It'd be great if you could try the search with other characters that ARE in the table to confirm those are working properly.

**Comment by clangen** [comment]
I found a bug in the script I wrote to generate the lookup/reverse lookup tables -- the character you are having problem with was included in the bad output. See commit: https://github.com/clangen/musikcube/commit/c4f3bc710b76b275ae7bce579b672191560da6ad

**Comment by khagaroth** [comment]
Ok, seems Š is the only issue (unless there are other missing characters), for whatever reason, the rest started working after I deleted and regenerated the library.

On a tangent is it expected to not be able to input some accented letters in the search input? I can't enter áéíó.

**Comment by clangen** [comment]
Hmm, I'm able to enter those characters on my mac using iTerm. 

<img width="762" alt="image" src="https://user-images.githubusercontent.com/2031666/209584426-d993d44d-9b33-4c4e-b455-d6831f429710.png">

What OS and terminal emulator are you using?

**Comment by clangen** [comment]
It appears to be Windows specific, and I think I understand the problem.

**Comment by clangen** [comment]
Fix here: https://github.com/clangen/musikcube/commit/a4f86a541ad24b01e4e1824bb6c43bef82a13812

**Comment by clangen** [comment]
New build released here: https://github.com/clangen/musikcube/releases/tag/0.99.3

Does this seem to work better?

**Comment by khagaroth** [comment]
Yep, 0.99.3 is fixed now.

**Comment by clangen** [comment]
Awesome! Closing.
